# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, camera_index: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
# 로깅 시스템 import
import time
# 시간 측정 및 제어용 import
from dataclasses import asdict, dataclass
# 데이터클래스 관련 함수들 import
from pathlib import Path
# 파일 경로 처리용 import
from pprint import pformat
# 예쁜 출력 포맷팅 함수 import
from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
# 카메라 설정 기본 클래스 import (사용되지 않아도 import)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
# OpenCV와 RealSense 카메라 설정 클래스들 import
from lerobot.configs import parser
#  LeRobot 설정 파서 import (명령줄 인수 처리용)
from lerobot.configs.policies import PreTrainedConfig
# 사전 훈련된 정책 설정 클래스 import
from lerobot.datasets.image_writer import safe_stop_image_writer
# 이미지 저장 작업의 안전한 중단을 위한 데코레이터 import
from lerobot.datasets.lerobot_dataset import LeRobotDataset
# LeRobot 데이터셋 클래스 import (HDF5 기반 데이터 저장)
from lerobot.datasets.utils import build_dataset_frame, hw_to_dataset_features
# 데이터셋 프레임 구성과 하드웨어-데이터셋 특성 변환 유틸리티
from lerobot.datasets.video_utils import VideoEncodingManager
# 비디오 인코딩 관리자 (카메라 이미지를 비디오로 압축)
from lerobot.policies.factory import make_policy
# 정책 팩토리 함수 (설정으로부터 정책 객체 생성)
from lerobot.policies.pretrained import PreTrainedPolicy
#  사전 훈련된 정책 클래스
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    hope_jr,
    koch_follower,
    my_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
)
# 로봇 관련 클래스들과 팩토리 함수들 import
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    my_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
# 텔레오퍼레이터 관련 클래스들과 팩토리 함수들 import
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
# 키보드 텔레오퍼레이션 클래스 import (이동 로봇용)
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
# 제어 관련 유틸리티들 import
from lerobot.utils.robot_utils import busy_wait
# 정밀한 타이밍 제어를 위한 busy_wait 함수
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
# 일반 유틸리티들: 안전한 PyTorch 디바이스, 로깅 초기화, 음성 출력
from lerobot.utils.visualization_utils import _init_rerun, log_rerun_data
# Rerun 시각화 관련 유틸리티들



# 데이터셋 기록 설정을 담을 데이터클래스 정의
# repo_id (str): Hugging Face Hub 상의 데이터셋 이름. "{사용자명}/{데이터셋명}" 형식.
# --dataset.repo_id 이런식으로 작성됨
# single_task (str): 녹화 중 수행하는 작업의 간단한 설명(예: "Pick the blue").
# root (str | Path | None): 데이터셋을 저장할 로컬 디렉터리 루트. None면 기본 위치.
# fps (int=30): 녹화 루프의 목표 프레임레이트. 제어 루프 주기 및 이미지/비디오 저장 간격 기준.
# episode_time_s (int|float=60): 1개 에피소드를 녹화하는 시간(초).
# reset_time_s (int|float=60): 각 에피소드 후 환경 리셋에 사용하는 시간(초).
# num_episodes (int=50): 녹화할 에피소드 개수(최대 반복 횟수).
# video (bool=True): 이미지 프레임을 비디오로 인코딩할지 여부. True면 비디오 생성.
# push_to_hub (bool=True): 녹화 완료 후 Hub에 업로드할지 여부.
# private (bool=False): Hub에 비공개 데이터셋으로 업로드할지 여부.
# tags (list[str] | None): Hub에 함께 업로드할 태그 목록.
# num_image_writer_processes (int=0): 이미지 저장에 사용할 서브프로세스 수. 0이면 프로세스 없이 스레드만 사용.
# num_image_writer_threads_per_camera (int=4): 카메라별 이미지 저장 스레드 수. 너무 크면 메인 쓰레드가 막혀 텔레옵 FPS 저하 가능.
# video_encoding_batch_size (int=1): 비디오 인코딩을 몇 개 에피소드 단위로 배치 처리할지. 1이면 매 에피소드 직후 인코딩.
@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # 데이터셋 식별자, HuggingFace Hub 저장소 형식 (예: "limdoyeon/robot-demos")
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # 기록 중 수행할 작업의 간단하고 정확한 설명
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # 데이터셋이 저장될 루트 디렉토리 (기본값: None)
    # Limit the frames per second.
    fps: int = 30
    # 초당 프레임 수 제한 (기본값: 30 FPS)
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # 각 에피소드의 데이터 기록 시간 (기본값: 60초)
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # 각 에피소드 후 환경 리셋 시간 (기본값: 60초)
    # Number of episodes to record.
    num_episodes: int = 50
    # 기록할 에피소드 수 (기본값: 50개)
    # Encode frames in the dataset into video
    video: bool = True
    # 데이터셋의 프레임을 비디오로 인코딩할지 여부 (기본값: True)
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # 데이터셋을 HuggingFace Hub에 업로드할지 여부 (기본값: True)
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # HuggingFace Hub에 비공개 저장소로 업로드할지 여부 (기본값: False)
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Hub의 데이터셋에 추가할 태그들 (기본값: None)
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # PNG로 프레임을 저장하는 서브프로세스 수 (기본값: 0 = 스레드만 사용)
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 12
    # 카메라당 PNG 이미지를 디스크에 쓰는 스레드 수 (기본값: 4)
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # 비디오 배치 인코딩 전에 기록할 에피소드 수 (기본값: 1 = 즉시 인코딩)

    def __post_init__(self):
    # 데이터클래스 생성 후 자동 호출되는 검증 메서드
        if self.single_task is None:
        # 작업 설명이 제공되지 않았으면
            raise ValueError("You need to provide a task as argument in `single_task`.")



# 전체 기록 설정을 담을 메인 데이터클래스 정의
@dataclass
class RecordConfig:
    robot: RobotConfig
    # 로봇 설정 (필수)
    # --robot.type=koch_follower, --robot.port=/dev/ttyACM0, --robot.cameras='{...}' 이런식으로 작성됨
    dataset: DatasetRecordConfig
    # --dataset.repo_id=... 이런식으로 작성됨
    # 데이터셋 기록 설정 (필수)
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # --teleop.type=koch_leader 이런식으로 작성됨
    # 텔레오퍼레이터로 로봇을 제어할지 여부 (선택사항)
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # --policy.path=... 이런식으로 작성됨
    # 정책으로 로봇을 제어할지 여부 (선택사항)
    # Display all cameras on screen
    display_data: bool = False
    # --display_data=true 이런식으로 작성됨
    # 모든 카메라를 화면에 표시할지 여부 (기본값: False)
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # --play_sounds=true 이런식으로 작성됨
    # 음성 합성으로 이벤트를 읽을지 여부 (기본값: True)
    # Resume recording on an existing dataset.
    resume: bool = False
    # --resume=true 이런식으로 작성됨
    # 기존 데이터셋에서 기록을 재개할지 여부 (기본값: False)

    def __post_init__(self):
    # 설정 클래스 생성 후 자동 호출되는 초기화 메서드
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        # 해킹: 사전 훈련된 정책 경로가 있는지 CLI 인수를 다시 파싱
        if policy_path:
        # 정책 경로가 제공되었으면
            cli_overrides = parser.get_cli_overrides("policy")
            # CLI에서 오버라이드된 정책 설정들 가져오기
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            # 사전 훈련된 설정을 로드하고 CLI 오버라이드 적용
            self.policy.pretrained_path = policy_path
            # 사전 훈련된 경로를 설정에 저장
        if self.teleop is None and self.policy is None:
        # 텔레오퍼레이터와 정책이 모두 None이면
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")
            # 에러 발생: "로봇을 제어하기 위해 정책, 텔레오퍼레이터 또는 둘 다 선택하세요"


    # 파서가 경로를 로드할 수 있게 하는 클래스 메서드   
    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]




# 이미지 저장 작업을 안전하게 중단하는 데코레이터
@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
# 실제 데이터 기록을 수행하는 메인 루프 함수
    if dataset is not None and dataset.fps != fps:
    # 데이터셋이 있고 FPS가 요청된 FPS와 다르면
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    # 팔 텔레오퍼레이터와 키보드 텔레오퍼레이터 변수 초기화
    if isinstance(teleop, list):
    # 텔레오퍼레이터가 리스트면 (다중 텔레오퍼레이터)
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        # 리스트에서 KeyboardTeleop 인스턴스 찾기
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(t, (so100_leader.SO100Leader, so101_leader.SO101Leader, koch_leader.KochLeader))
            ),
            None,
        )
        # 리스트에서 팔 텔레오퍼레이터 인스턴스 찾기
        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )
        # 팔과 키보드 텔레오퍼레이터가 있지 않거나, 리스트 길이가 2가 아니거나, 로봇이 lekiwi가 아니면

    # if policy is given it needs cleaning up
    if policy is not None:
        policy.reset()

    timestamp = 0
    # 타임스탬프 초기화
    start_episode_t = time.perf_counter()
    # 에피소드 시작 시간 기록
    while timestamp < control_time_s:
    # 제어 시간 동안 반복
        start_loop_t = time.perf_counter()
        # 루프 시작 시간 기록
        if events["exit_early"]:
        # 조기 종료 이벤트가 발생했으면
            events["exit_early"] = False
            # 이벤트 플래그 리셋
            break

        observation = robot.get_observation()
        # 로봇에서 현재 관찰 데이터 읽기 (모터 위치 + 카메라 이미지들)

        if policy is not None or dataset is not None:
        # 정책이나 데이터셋이 있으면
            observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")
            # 관찰 데이터를 데이터셋 프레임 형식으로 변환

        
        if policy is not None:
        # 정책이 있으면 (AI 자동 제어)
            action_values = predict_action(
                observation_frame,
                policy,
                get_safe_torch_device(policy.config.device),
                policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
            # 정책을 사용해 다음 행동 예측 (AI가 결정한 모터 목표 위치들)
            action = {key: action_values[i].item() for i, key in enumerate(robot.action_features)}
            # 예측된 행동을 딕셔너리 형태로 변환
        elif policy is None and isinstance(teleop, Teleoperator):
        # 정책이 없고 텔레오퍼레이터가 단일 객체면
            action = teleop.get_action()
            # 텔레오퍼레이터에서 현재 동작 읽기 (사용자가 조작하는 위치들)
        elif policy is None and isinstance(teleop, list):
        # 정책이 없고 텔레오퍼레이터가 리스트면 (다중 텔레오퍼레이션)
            # TODO(pepijn, steven): clean the record loop for use of multiple robots (possibly with pipeline)
            arm_action = teleop_arm.get_action()
            # 팔 텔레오퍼레이터에서 동작 읽기
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            # 팔 동작에 "arm_" 접두사 추가
            keyboard_action = teleop_keyboard.get_action()
            # 키보드 텔레오퍼레이터에서 동작 읽기
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            # 키보드 입력을 로봇 베이스 동작으로 변환
            action = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            # 팔 동작과 베이스 동작을 결합 (베이스 동작이 있으면)
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset.
        sent_action = robot.send_action(action)
        # 로봇에 동작 전송 (max_relative_target으로 제한될 수 있으므로 실제 전송된 동작 반환)
        if dataset is not None:
        # 데이터셋이 있으면 (기록 중이면
            action_frame = build_dataset_frame(dataset.features, sent_action, prefix="action")
            frame = {**observation_frame, **action_frame}
            # 실제 전송된 동작을 데이터셋 프레임 형식으로 변환
            # 관찰과 동작 프레임을 결합
            dataset.add_frame(frame, task=single_task)
            # 데이터셋에 프레임 추가 (observation + action 쌍 저장)


        if display_data:
        #  데이터 표시가 활성화되어 있으면
            log_rerun_data(observation, action)
            # Rerun 뷰어에 데이터 전송 (3D 시각화)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)
        # 정확한 FPS 유지를 위한 대기

        timestamp = time.perf_counter() - start_episode_t
        


# CLI 파서 래퍼 데코레이터
@parser.wrap()
# @parser.wrap()가 CLI 인수들을 읽어 RecordConfig와 그 하위 DatasetRecordConfig/RobotConfig/TeleoperatorConfig로 변환합니다.
# 예: --dataset.repo_id=... → cfg.dataset.repo_id
# 예: --robot.type=koch_follower, --robot.port=/dev/ttyACM0, --robot.cameras='{...}' → cfg.robot 안쪽 필드들
# 예: --teleop.type=koch_leader → cfg.teleop
# 예: --display_data=true → cfg.display_data
def record(cfg: RecordConfig) -> LeRobotDataset:
# 메인 기록 함수 정의
    init_logging()
    # 로깅 시스템 초기화
    logging.info(pformat(asdict(cfg)))
    # 설정 정보를 로그로 출력
    if cfg.display_data:
    # 조건 검사: --display_data=true로 설정되었는지 확인
    # True면 실시간 3D 시각화 활성화 준비
        _init_rerun(session_name="recording")
        # Rerun 초기화: 3D 시각화 뷰어 시작
        # session_name="recording": 세션 이름 설정
        # 웹 브라우저에서 실시간으로 로봇 상태/카메라 영상 볼 수 있음
    robot = make_robot_from_config(cfg.robot)
    # 로봇 객체 생성: 설정에 따라 로봇 인스턴스 생성
    # cfg.robot.type에 따라 다른 로봇 클래스 선택:
    # "koch_follower" → KochFollower 클래스
    # "so100_follower" → SO100Follower 클래스
    # 포트, 카메라, ID 등 모든 설정이 로봇 객체에 적용됨
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None
    # 조건부 텔레오퍼레이터 생성:
    # cfg.teleop is not None: 텔레오퍼레이터 설정이 있으면
    # make_teleoperator_from_config(cfg.teleop): 텔레오퍼레이터 객체 생성
    # 없으면 None (정책만으로 제어하거나 수동 리셋용)
    action_features = hw_to_dataset_features(robot.action_features, "action", cfg.dataset.video)
    # 액션 특성 변환: 하드웨어 액션을 데이터셋 형식으로 변환
    # robot.action_features: 로봇이 제어할 수 있는 관절들 (예: ["arm_joint_1", "arm_joint_2", "gripper"])
    # "action": 접두사로 "action.arm_joint_1" 형태가 됨
    # cfg.dataset.video: 비디오 사용 여부에 따라 저장 방식 결정
    obs_features = hw_to_dataset_features(robot.observation_features, "observation", cfg.dataset.video)
    # 관찰 특성 변환: 하드웨어 센서 데이터를 데이터셋 형식으로 변환
    # robot.observation_features: 로봇이 읽을 수 있는 센서들
    # 관절 위치: ["arm_joint_1", "arm_joint_2"]
    # 카메라: {"laptop": CameraConfig, "wrist": CameraConfig}
    # 결과: "observation.state.arm_joint_1", "observation.images.laptop" 등
    dataset_features = {**action_features, **obs_features}
    # 액션과 관찰 특성을 결합
    # 특성 합병: 액션과 관찰 특성을 하나의 딕셔너리로 결합
    # ** 연산자: 딕셔너리 언패킹 (두 딕셔너리 내용을 합침)
    # 최종결과
    #     {
    #     "action.arm_joint_1": {"dtype": "float32"},
    #     "observation.state.arm_joint_1": {"dtype": "float32"},  
    #     "observation.images.laptop": {"shape": [480, 640, 3], "dtype": "uint8"}
    # }



    if cfg.resume:
    # 재개 모드 검사: --resume=true로 기존 데이터셋 이어서 기록할 건지
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )
        # 기존 데이터셋 로드: 이미 존재하는 데이터셋 폴더에서 로드
        # cfg.dataset.repo_id: 예) "aliberts/pick-cube"
        # root=cfg.dataset.root: 로컬 저장 경로 (None이면 기본 캐시 디렉토리)
        # batch_encoding_size: 몇 개 에피소드씩 모아서 비디오 인코딩할지
        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
        # 영상 데이터 저장을 하지 않기 위해서 패스함
        # 로봇에 카메라가 있으면
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
            # 이미지 저장 작업 시작 (멀티프로세싱/멀티스레딩으로)
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        # 데이터셋과 로봇의 호환성 검사

    else:
    # 새 데이터셋 생성 모드면
    # 데이터셋 이름 유효성 검사:
    # HuggingFace Hub 규칙에 맞는 이름인지 확인 (예: "사용자명/데이터셋명")
    # 정책과 데이터셋 이름이 충돌하지 않는지 검사
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        # 데이터셋 이름 유효성 검사
        # 이걸로 인해 만들어질 데이터 셋 구조는 이렇게 된다
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )
        # 새 LeRobot 데이터셋 생성 (HDF5 파일 + 메타데이터)
    # cfg.dataset.repo_id: 데이터셋 이름
    # cfg.dataset.fps: 30 (초당 30프레임으로 기록)
    # robot_type=robot.name: 로봇 타입 메타데이터에 저장
    # features=dataset_features: 앞서 만든 데이터 스키마
    # use_videos=cfg.dataset.video: 비디오 압축 사용할지 (True/False)
    # image_writer_processes: 이미지 저장용 서브프로세스 개수 (0 = 스레드만)
    # image_writer_threads: 총 스레드 개수 (카메라당 스레드 수 × 카메라 개수)
    # Load pretrained policy
    # 생성되는 폴더 구조
    # ├── data/           # HDF5 파일들
    # ├── videos/         # MP4 파일들  
    # ├── meta.json       # 메타데이터
    # └── README.md       # 자동 생성 문서
    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
    # 정책 설정이 있으면 사전 훈련된 정책 로드
    robot.connect()
    # 로봇에 연결 (모터 + 카메라 연결)
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop=teleop,
                policy=policy,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
            ):
                log_say("Reset the environment", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer()
                continue
            

            # 에피소드 저장
            dataset.save_episode()
            recorded_episodes += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)
    # 기록 중지 학습 중지 
    
    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    dataset = record()
    
    try:
        import subprocess
        import sys
        
        # 간단한 작업 타입 판단
        def get_task_type():
            full_info = ' '.join(sys.argv).lower()
            if hasattr(dataset, 'meta') and hasattr(dataset.meta, 'single_task'):
                full_info += " " + str(dataset.meta.single_task).lower()
            
            if any(keyword in full_info for keyword in ['pick_place', 'safebox', 'box', 'place']):
                return 'pick_place'
            return 'button_task'
        
        # ✅ conda 환경 완전 비활성화하고 시스템 Python 사용
        task_type = get_task_type()
        topic = '/robot_arm/pick_and_place_end' if task_type == 'pick_place' else '/robot_arm/button_end'
        
        # 시스템 환경에서만 실행하는 스크립트
        ros_command = f'''
# conda 환경 완전 비활성화
unset CONDA_PREFIX
unset CONDA_DEFAULT_ENV
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# 시스템 ROS2 환경 설정
source /opt/ros/humble/setup.bash
export ROS_DOMAIN_ID=77

echo "🔄 시스템 ROS2 환경에서 완료 신호 발행 중..."

# 시스템 Python으로 ROS2 실행
/usr/bin/python3 -c "
import rclpy
from rclpy.node import Node
from std_msgs.msg import Empty
import time

print('🔄 ROS2 초기화 중...')
rclpy.init()
node = Node('lerobot_completion')
pub = node.create_publisher(Empty, '{topic}', 10)

# 구독자 대기
for i in range(20):
    if pub.get_subscription_count() > 0:
        print(f'✅ 구독자 {{pub.get_subscription_count()}}명 발견!')
        break
    print(f'⏳ 구독자 대기 중... {{i+1}}/20')
    time.sleep(0.5)

# 완료 신호 발행
msg = Empty()
pub.publish(msg)
print('📡 완료 신호 발행 완료!')
time.sleep(2)

node.destroy_node()
rclpy.shutdown()
print('✅ 완료 신호 발행 성공: {topic}')
"

echo "🎉 완료!"
sleep 3
exit
'''
        
        # 새 터미널에서 실행
        subprocess.Popen([
            'gnome-terminal', 
            '--', 
            'bash', 
            '-c', 
            ros_command
        ])
        
        task_name = '상자 적재' if task_type == 'pick_place' else '버튼 작업'
        print(f"🎉 LeRobot 작업 완료! {task_name} 완료 신호를 시스템 환경에서 발행합니다.")
        
    except Exception as e:
        print(f"❌ 완료 신호 발행 실패: {e}")
        print("LeRobot 작업은 정상적으로 완료되었습니다.")


if __name__ == "__main__":
    main()
